name: nov24batch5pm
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.4.1
  intl_phone_field: ^3.2.0
  image_picker: ^1.1.2
  intl: ^0.20.1
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.0
  http: ^1.2.2
  url_launcher: ^6.3.1
  location: ^7.0.1
  app_settings: ^5.1.1
  infinite_scroll_pagination: ^4.1.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - atul/
    - images/
